CREATE TABLE DEPARTEMENT (ID INTEGER AUTO_INCREMENT NOT NULL, nom VARCHAR(25), PRIMARY KEY (ID))
CREATE TABLE Employe (ID INTEGER AUTO_INCREMENT NOT NULL, Date_embauche DATE, Nom VARCHAR(25), dt_fk INTEGER, PRIMARY KEY (ID))
ALTER TABLE Employe ADD CONSTRAINT FK_Employe_dt_fk FOREIGN KEY (dt_fk) REFERENCES DEPARTEMENT (ID)
